Feat/Ev 802/flutter 05 rota com argumentos grafico
NillWarren/everest-cryptos pull request #4
Opened 2022-09-20 16:11 UTC by NillWarren

Rota para retorno a tela de portfólio funcional.

Valor da moeda e variação do mercado variarem conforme alteração do período do gráfico.

Botão com função do clique.

Uso da lib fl_chart.

Componetização

2022-09-20 18:03 UTC, GuilhermePedroMilani approved these changes

2022-09-21 14:18 UTC, CarlosTSIlva requested changes

2022-09-21 14:18 UTC, CarlosTSIlva commented on lib/main.dart
> +      },
onGenerate routes usa ele

2022-09-21 14:18 UTC, CarlosTSIlva commented on lib/presenter/details/widgets/graphic_thirty_days.dart
> +              ],
Tenta separar isso pra um mock ou um model mock

2022-09-21 14:18 UTC, CarlosTSIlva commented on lib/presenter/details/widgets/body_graphic.dart
> +        return const Graphic5Days();
Pode remover esse default porque ele so vai entrar nos casos de uso

2022-09-21 14:18 UTC, CarlosTSIlva commented on lib/presenter/details/widgets/graphic_ ninety_days.dart
> +                const FlSpot(44.5, 8.5),
Gerar o model ou mock model como preferir pra n ficar isso na tela

2022-09-22 14:31 UTC, CarlosTSIlva approved these changes

2022-09-22 14:40 UTC, NillWarren commented on lib/main.dart
> +      },
feito

2022-09-22 14:40 UTC, NillWarren commented on lib/presenter/details/widgets/graphic_thirty_days.dart
> +              ],
modificação feita

2022-09-22 14:41 UTC, NillWarren commented on lib/presenter/details/widgets/body_graphic.dart
> +        return const Graphic5Days();
modificação feita

2022-09-22 14:41 UTC, NillWarren commented on lib/presenter/details/widgets/graphic_ ninety_days.dart
> +                const FlSpot(44.5, 8.5),
modificação feita

2022-09-22 18:10 UTC, merged